package Modelo;
// Generated 9/04/2018 09:09:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Usuario usuario;
     private String descripcion;
     private String titulo;
     private String tema;
     private Date fecha;
     private Set comentarios = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, String descripcion, String titulo, String tema, Date fecha) {
        this.idPregunta = idPregunta;
        this.descripcion = descripcion;
        this.titulo = titulo;
        this.tema = tema;
        this.fecha = fecha;
    }
    public Pregunta(int idPregunta, Usuario usuario, String descripcion, String titulo, String tema, Date fecha, Set comentarios) {
       this.idPregunta = idPregunta;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.titulo = titulo;
       this.tema = tema;
       this.fecha = fecha;
       this.comentarios = comentarios;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


