package Modelo;
// Generated 9/04/2018 09:09:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String correo;
     private String nombre;
     private Long foto;
     private String contrasenia;
     private String FRegistro;
     private boolean esAdmin;
     private String sesion;
     private Set comentarios = new HashSet(0);
     private Set preguntas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String correo, String nombre, String contrasenia, String FRegistro, boolean esAdmin) {
        this.idUsuario = idUsuario;
        this.correo = correo;
        this.nombre = nombre;
        this.contrasenia = contrasenia;
        this.FRegistro = FRegistro;
        this.esAdmin = esAdmin;
    }
    public Usuario(int idUsuario, String correo, String nombre, Long foto, String contrasenia, String FRegistro, boolean esAdmin, String sesion, Set comentarios, Set preguntas) {
       this.idUsuario = idUsuario;
       this.correo = correo;
       this.nombre = nombre;
       this.foto = foto;
       this.contrasenia = contrasenia;
       this.FRegistro = FRegistro;
       this.esAdmin = esAdmin;
       this.sesion = sesion;
       this.comentarios = comentarios;
       this.preguntas = preguntas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getFoto() {
        return this.foto;
    }
    
    public void setFoto(Long foto) {
        this.foto = foto;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getFRegistro() {
        return this.FRegistro;
    }
    
    public void setFRegistro(String FRegistro) {
        this.FRegistro = FRegistro;
    }
    public boolean isEsAdmin() {
        return this.esAdmin;
    }
    
    public void setEsAdmin(boolean esAdmin) {
        this.esAdmin = esAdmin;
    }
    public String getSesion() {
        return this.sesion;
    }
    
    public void setSesion(String sesion) {
        this.sesion = sesion;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


