-- Script para crear las tablas necesarias de esta iteración.

CREATE TABLE PREGUNTA(
ID_Pregunta INTEGER PRIMARY KEY,
Descripcion VARCHAR2(50) NOT NULL,
Titulo VARCHAR2(50) NOT NULL,
Tema VARCHAR2(50) NOT NULL
);

CREATE TABLE COMENTARIO(
ID_Com INTEGER PRIMARY KEY,
Contenido VARCHAR2(50) NOT NULL,
VOTOS INTEGER NOT NULL
);

CREATE TABLE USUARIO(
ID_Usuario INTEGER PRIMARY KEY,
Correo VARCHAR2(50) NOT NULL,
Nombre VARCHAR2(50) NOT NULL,
Foto BLOB,
Contrasenia VARCHAR2(15) NOT NULL,
F_Registro VARCHAR2(50) NOT NULL,
Es_Admin BOOLEAN NOT NULL,
Sesion VARCHAR2(50)
);
